[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "npm start & sleep 5 ; npx prisma db push --accept-data-loss ; npm run seed"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[doc]
help = "Sistema de Gestión de Mantenimiento de Climatización - Backend"
